name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print Greetings
        run: echo "Hello world by Girish"
      - name: Print Goodbye 2022
        run: echo "done Bye!"
    
  
